name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Installing packages
        run: |
          python -m pip install --upgrade pip
          pip install -r DRF_todo/requirements.txt
  build_images:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag DRF_todo
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Add tag
      run: docker tag DRF_todo docker.pkg.github.com/tosuvs/DRF_todo/DRF_todo
    - name: Push new image
      run: docker push docker.pkg.github.com/tosuvs/DRF_todo/DRF_todo
